package com.company;

public enum PanstwaNazwy {

    URUGUAY, POLAND, CANADA, USA, GREENLAND, CENTRAL_AMERICA, ARGENTINA, BRASIL, PERU, VENEZUELA,
    GREAT_BRITAIN, ICELAND, SCANDINAVIA, SOUTHERN_EUROPE, EASTERN_EUROPE, WESTERN_EUROPE, CONGO,
    EAST_AFRICA, MADAGASCAR, EGYPT, NORTH_AFRICA, SOUTH_AFRICA, AFGHANISTAN, CHINA, INDIA, RUSSIA,
    JAPAN, MONGOLIA, SOUTHEAST_ASIA, AUSTRALIA, INDONESIA, NEW_GUINEA, MiDDLE_EAST
}
